apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-app
spec:
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70

# Made with Bob
