---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

## Read data using RJDBC
```{r}
library(ibmWatsonStudioLib)
wslib <- access_project_or_space()
Db2_WoC_metadata = wslib$get_connection("Db2 WoC")

library(RJDBC)

drv <- JDBC(driverClass="com.ibm.db2.jcc.DB2Driver", classPath="/opt/ibm/connectors/db2/db2jcc4.jar",  identifier.quote = "\"")

Db2_WoC_url <- paste("jdbc:db2://",
    Db2_WoC_metadata[][["host"]],
    ":", Db2_WoC_metadata[][["port"]],
    "/", Db2_WoC_metadata[][["database"]],
    ":", "sslConnection=true;",
    sep=""
)

Db2_WoC_connection <- dbConnect(drv,
    Db2_WoC_url,
    Db2_WoC_metadata[][["username"]],
    Db2_WoC_metadata[][["password"]]
)

query <- "SELECT * FROM \"HMCRD\".\"APPLICATION_TRAIN\" FETCH FIRST 10000 ROWS ONLY"

data <- dbSendQuery(Db2_WoC_connection, query)

Train <- dbFetch(data, n = 10000)

head(Train)
```

## Write data

The Batch error we saw earlier is due the NA values in the dataframe.

```
execute JDBC update query failed in dbSendUpdate ([jcc][t4][102][10040][4.22.29] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null)
```
As a workaround, we replaced NAs with "".

```{r}
Train[is.na(Train)] <- ""
dbWriteTable(Db2_WoC_connection, Id(schema="HMCRD", table="SAVE_DEMO"), Train, overwrite=TRUE)
```

```{r}
query <- "SELECT * FROM \"HMCRD\".\"SAVE_DEMO\" FETCH FIRST 10000 ROWS ONLY"

data <- dbSendQuery(Db2_WoC_connection, query)

save_demo <- dbFetch(data, n = 10000)

dim(save_demo)
```

## Delete a table
```{r}
dbSendUpdate(Db2_WoC_connection, "drop table HMCRD.SAVE_DEMO")
```


## Using RStudio Connections:
```{r eval=FALSE}
conn_string <- paste0("Driver={Db2};Database=BLUDB;Hostname=", Db2_WoC_metadata[][["host"]],
       ";Port=", Db2_WoC_metadata[][["port"]],
       ";Protocol=TCPIP",
       ";Uid=", Db2_WoC_metadata[][["username"]],
       ";Pwd=", Db2_WoC_metadata[][["password"]],
       ";Security=SSL")
```

```{r eval=FALSE}
library(DBI)
con <- dbConnect(odbc::odbc(), .connection_string = conn_string, timeout = 10, )
```

This will pull out tables in the connections tab. You can use this connection to write tables the same way as we did with the JDBC connection.
```{r}
#dbWriteTable(con, Id(schema="HMCRD", table="SAVE_DEMO2"), Train, overwrite=TRUE)
#dbSendUpdate(con, "drop table HMCRD.SAVE_DEMO2")
```

## Close connections
```{r}
dbDisconnect(Db2_WoC_connection)
```

